/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "../../include/ams_types.h"
#include "../../include/system_clock.h"
#include "../../include/errno.h"
#include "../../include/uart_driver.h"
#include "../../include/spi_driver.h"
#include "../../include/i2c_driver.h"
#include <p24fxxxx.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_pic_init();
extern void test_uart_init();
extern void test_uart_baud_rate();
extern void test_uart_read();
extern void test_spi_init();
extern void test_spi_speed();
extern void test_i2c_init();
extern void test_i2c_speed();


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
#ifdef UNITY_TEST
int main(void)
{
  UnityBegin("..\test\test_all.c");
  RUN_TEST(test_pic_init, 60);
  RUN_TEST(test_uart_init, 86);
  RUN_TEST(test_uart_baud_rate, 93);
  RUN_TEST(test_uart_read, 105);
  RUN_TEST(test_spi_init, 112);
  RUN_TEST(test_spi_speed, 136);
  RUN_TEST(test_i2c_init, 157);
  RUN_TEST(test_i2c_speed, 165);

  return (UnityEnd());
}
#endif
